Fix Inflector deprecations
oroinc/doctrine-extensions pull request #69
Opened 2020-07-09 13:03 UTC by maciejmrozinski

Deprecation: The "Doctrine\Common\Inflector\Inflector::classify" method is deprecated and will be dropped in doctrine/inflector 2.0. Please update to the new Inflector API.

1. updating min PHP version to 7.0 since Doctrine Inflector (old and new one) is using parameter types (like `string`) so it's needed anyway
2. using new Inflector API if possible (from Inflector >= 1.4.0)

2020-07-09 13:26 UTC, hacfi commented on src/Oro/ORM/Query/AST/FunctionFactory.php
> +        } else {
no else necessary: just do
```
}

return LegacyInflector::classify($platformName);
```

2020-07-09 14:09 UTC, maciejmrozinski commented on src/Oro/ORM/Query/AST/FunctionFactory.php
> +        } else {
done

2020-07-09 15:15 UTC, orocla commented
Thank you for your pull request.

It looks like this may be your first contribution to an Oro, Inc. open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at https://oroinc.com/b2b-ecommerce/contributor-license-agreement/

If you've already signed the CLA, it's possible we don't have your GitHub username or you're using a different email address. GitHub uses the email address you set in your local Git configuration to associate commits with your GitHub account. Please sign the CLA again using the correct GitHub username and email address or see this help article on [setting the email on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

Once you've signed the CLA, please allow for some time for the submission to be processed.

2020-08-13 15:53 UTC, TheRichCourt commented
@orocla Is this repo still maintained? This PR looks good, and would solve some problems for me.

Dropping PHP 5 support seems sensible at this point, given 7.2 is already the oldest supported version https://www.php.net/supported-versions.php

2020-08-13 16:41 UTC, mbessolov commented
@maciejmrozinski @hacfi thank you for the contribution.

_(internal reference BAP-20092)_

2020-08-31 11:47 UTC, x86demon requested changes
This PR doesn't pass all CI checks. Please remove PHP 5.x builds and add newer versions of PHP to the build matrix

2020-08-31 11:47 UTC, x86demon commented on src/Oro/ORM/Query/AST/FunctionFactory.php
> +    private static function classify($platformName)
Please, change signature to `classify($word)` as $platformName doesn't represent the parameter purpose

2020-08-31 11:47 UTC, x86demon commented on src/Oro/ORM/Query/AST/FunctionFactory.php
> +     * @var Inflector
Might be null.
Should be `@var Inflector|null`

2020-09-08 09:26 UTC, nicolasfrey approved these changes

2020-10-29 18:40 UTC, dxops commented
I don't believe we need Inflector here, just copy it's single method implementation. like https://github.com/oroinc/doctrine-extensions/pull/67/files#diff-f66b8df2cb759a1d790523f1b2baacc7c72e47078ed2772356a34fa2fc661143R44-R46

2020-11-23 08:55 UTC, michaljusiega commented
Friendly ping: @maciejmrozinski @hacfi

2020-11-23 09:36 UTC, maciejmrozinski commented
Will try to address all comments and changes today/tomorrow. Sorry for delay, I totally forgot about this PR.

2020-12-07 14:49 UTC, Tilotiti commented
It's now broken. See #71

2020-12-08 04:35 UTC, mbessolov commented
I second what @dxops said above - we do not need to use Inflector here at all.
One of the reasons why they now have non-static inflector is so that it can work differently in different languages (locales).
We do not want the classify method results change based on the system locale, so it totally makes sense to have this one line function implemented here (exactly as in https://github.com/oroinc/doctrine-extensions/pull/67/files#diff-f66b8df2cb759a1d790523f1b2baacc7c72e47078ed2772356a34fa2fc661143R39-R47)  instead of dragging in Inflector as the dependency just for the sake of this one line. Just look at the recent changes here - there is now more scaffolding code around calling the correct class's method  than what the implemention of the classify would be itself.

2020-12-16 15:53 UTC, vladyslavstartsev commented
Hello to every one, I would like to get this merged ASAP (since it's broken on 2.8 ORM version). Is there a way for me to help with this?

2020-12-17 16:29 UTC, mbessolov commented
This PR has been replaced by #72

2020-12-17 16:29 UTC, closed without merging

2020-12-17 16:29 UTC, mbessolov commented
I've just tagged 1.3.1 - it no longer uses Doctrine Inflector.